// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvfxmhswlhpqwypzgrhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12ZnhtaHN3bGhwcXd5cHpncmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTM3MjgsImV4cCI6MjA3Mzg2OTcyOH0.Y_c_KKwas-ZN88qmdWsAq3BuWUC3zQHDvglwKy_JoRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});